# Generated by Django 5.1.5 on 2025-01-14 20:28

import proposals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название проекта.', max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(help_text='Подробно опишите детали проекта.', verbose_name='Описание проекта')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Укажите бюджет проекта в валюте (₸).', max_digits=10, verbose_name='Бюджет')),
                ('deadline', models.DateField(help_text='Укажите крайний срок завершения проекта.', verbose_name='Крайний срок')),
                ('applicant_name', models.CharField(help_text='Введите полное имя заявителя.', max_length=255, verbose_name='Имя заявителя')),
                ('applicant_email', models.EmailField(help_text='Укажите адрес электронной почты для обратной связи.', max_length=254, verbose_name='Email заявителя')),
                ('applicant_phone', models.CharField(help_text='Укажите контактный номер телефона.', max_length=15, verbose_name='Телефон заявителя')),
                ('attachments', models.FileField(help_text='Загрузите файл(-ы), относящийся к проекту.', upload_to=proposals.models.project_attachment_path, verbose_name='Вложения')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='new', help_text='Выберите текущий статус заявки.', max_length=10, verbose_name='Статус заявки')),
                ('decision_comment', models.TextField(blank=True, help_text='Добавьте комментарий об одобрении или отклонении заявки.', null=True, verbose_name='Комментарий руководства')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Автоматически сохраняет дату и время создания заявки.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Автоматически обновляется при внесении изменений.', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
